#!/bin/sh

if [ "$1" = "autoconf" ]; then
    if [ -x /root/sqlsize.sh ]; then
        /root/sqlsize.sh ipdr > /dev/null
        if [ $? = "0" ]; then
                echo yes
                exit 0
        else
                    echo no
                    exit 0
            fi
    else
        echo no
        exit 0
    fi
fi


if [ "$1" = "config" ]; then
        echo 'graph_title SQL Table Size'
        echo 'graph_args --base 1000 -l 0'
        echo 'graph_vlabel sql'
        echo 'graph_noscale true'
        echo 'graph_category system'
        echo 'sql.label sql'
        echo 'sql.warning 10'
        echo 'sql.critical 120'
        echo 'graph_info SQL Table size of day.'
        echo 'sql.info SQL Table size of day.'

        exit 0
fi


echo -n "ipdr.value "
/root/sqlsize.sh ipdr

echo -n "udr.value "
/root/sqlsize.sh udr




#############
# root@ipdr1:/usr/local/etc/munin/plugins # ll sql
# lrwxr-xr-x  1 root  wheel  34 Oct  3 17:01 sql@ -> /usr/local/share/munin/plugins/sql
